# Q2_Part TWO
- use employee_compensation dataset.
- Filter out the result based on only Calendar year data
- Find average of all types of compensation for each employee
- List out the employees whose overtime salary is greater than 5% of their salary
- For each job family calculate Percentage of total benefits based on average total benefits and average total compensation
- Generate CSV for all the employee records with overtime salary is greater than 5% of their salary
- Generate CSV with 4 columns(Job family, Total benefits, Total Compensation and percentage of total benefits)

In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
#getting current working directory
b = os.getcwd()

#reading the csv file
df = pd.read_csv(b+"\\"+"Data\\employee_compensation.csv", usecols=[0,1,9,11,12,13,14,15,16,17,18,19,20,21])

In [3]:
#printing the top 5 records of the data frame
df.head()

,Year Type,Year,Job Family,Job,Employee Identifier,Salaries,Overtime,Other Salaries,Total Salary,Retirement,Health/Dental,Other Benefits,Total Benefits,Total Compensation
0,Calendar,2013,Journeyman Trade,Plumber,52206,98528.52,0.00,3955.59,102484.11,20142.55,12918.24,8371.76,41432.55,143916.66
1,Fiscal,2015,Dietary & Food,Senior Food Service Supervisor,52950,69169.82,755.02,4179.08,74103.92,15641.92,12499.30,5669.02,33810.24,107914.16
2,Calendar,2016,Management,"Bdcomm Mbr, Grp2,M=$25/Mtg",33958,200.00,0.00,0.00,200.00,0.00,51.45,15.83,67.28,267.28
3,Calendar,2016,Legal & Court,Invstgtor Ofc Citizen Cmplnts,33073,1783.00,0.00,0.00,1783.00,325.05,257.23,153.85,736.13,2519.13
4,Fiscal,2015,Public Service Aide,Public Service Trainee,15849,1102.50,0.00,0.00,1102.50,0.00,538.82,85.36,624.18,1726.68

In [4]:
#filtering data for only Calendar year type
Cal_Data = df[df['Year Type'] == "Calendar"]

Cal_Data.head()

,Year Type,Year,Job Family,Job,Employee Identifier,Salaries,Overtime,Other Salaries,Total Salary,Retirement,Health/Dental,Other Benefits,Total Benefits,Total Compensation
0,Calendar,2013,Journeyman Trade,Plumber,52206,98528.52,0.00,3955.59,102484.11,20142.55,12918.24,8371.76,41432.55,143916.66
2,Calendar,2016,Management,"Bdcomm Mbr, Grp2,M=$25/Mtg",33958,200.00,0.00,0.00,200.00,0.00,51.45,15.83,67.28,267.28
3,Calendar,2016,Legal & Court,Invstgtor Ofc Citizen Cmplnts,33073,1783.00,0.00,0.00,1783.00,325.05,257.23,153.85,736.13,2519.13
5,Calendar,2016,"Clerical, Secretarial & Steno",Principal Clerk,23930,80207.24,2232.53,1568.00,84007.77,15064.98,13890.29,6888.51,35843.78,119851.55
7,Calendar,2014,Public Service Aide,Publ Svc Aide-Asst To Prof,38054,24180.00,0.00,0.00,24180.00,1490.20,8586.13,1880.37,11956.70,36136.70

In [5]:
#Calculating the mean of all the different types of salary columns
AvgSal = Cal_Data.groupby(['Year','Job Family','Job','Employee Identifier']).mean()

In [6]:
#printing the first 5 records of the resultant dataset
AvgSal.head()

                                                                                                  Salaries  \
Year Job Family                    Job                                      Employee Identifier
2013 Administrative & Mgmt (Unrep) Administrator, Department Of Public Heal 25462                 42507.36
                                   Dep Dir For Investments, Ret             28784                315572.01
                                   Mayor                                    2321                 285446.37
                                   Youth Comm Advisor                       22651                 13915.80
                                                                            44553                 41712.54

                                                                                                 Overtime  \
Year Job Family                    Job                                      Employee Identifier
2013 Administrative & Mgmt (Unrep) Administrator, Department Of Public Heal 25462                     0.0
                                   Dep Dir For Investments, Ret             28784                     0.0
                                   Mayor                                    2321                      0.0
                                   Youth Comm Advisor                       22651                     0.0
                                                                            44553                     0.0

                                                                                                 Other Salaries  \
Year Job Family                    Job                                      Employee Identifier
2013 Administrative & Mgmt (Unrep) Administrator, Department Of Public Heal 25462                          0.00
                                   Dep Dir For Investments, Ret             28784                          0.00
                                   Mayor                                    2321                           0.00
                                   Youth Comm Advisor                       22651                       5296.91
                                                                            44553                          0.00

                                                                                                 Total Salary  \
Year Job Family                    Job                                      Employee Identifier
2013 Administrative & Mgmt (Unrep) Administrator, Department Of Public Heal 25462                    42507.36
                                   Dep Dir For Investments, Ret             28784                   315572.01
                                   Mayor                                    2321                    285446.37
                                   Youth Comm Advisor                       22651                    19212.71
                                                                            44553                    41712.54

                                                                                                 Retirement  \
Year Job Family                    Job                                      Employee Identifier
2013 Administrative & Mgmt (Unrep) Administrator, Department Of Public Heal 25462                   8850.04
                                   Dep Dir For Investments, Ret             28784                  60454.87
                                   Mayor                                    2321                   54710.50
                                   Youth Comm Advisor                       22651                   2534.05
                                                                            44553                   8790.67

                                                                                                 Health/Dental  \
Year Job Family                    Job                                      Employee Identifier
2013 Administrative & Mgmt (Unrep) Administrator, Department Of Public Heal 25462                      1913.81
                                   Dep Dir For Investments, Ret             28784                     12918.24
                                   Mayor                                    2321                      12918.24
                                   Youth Comm Advisor                       22651                      2870.73
                                                                            44553                     10047.52

                                                                                                 Other Benefits  \
Year Job Family                    Job                                      Employee Identifier
2013 Administrative & Mgmt (Unrep) Administrator, Department Of Public Heal 25462                       1595.28
                                   Dep Dir For Investments, Ret             28784                      14798.64
                                   Mayor                                    2321                       13443.75
                                   Youth Comm Advisor                       22651                       1533.80
                                                                            44553                       3313.20

                                                                                                 Total Benefits  \
Year Job Family                    Job                                      Employee Identifier
2013 Administrative & Mgmt (Unrep) Administrator, Department Of Public Heal 25462                      12359.13
                                   Dep Dir For Investments, Ret             28784                      88171.75
                                   Mayor                                    2321                       81072.49
                                   Youth Comm Advisor                       22651                       6938.58
                                                                            44553                      22151.39

                                                                                                 Total Compensation
Year Job Family                    Job                                      Employee Identifier
2013 Administrative & Mgmt (Unrep) Administrator, Department Of Public Heal 25462                          54866.49
                                   Dep Dir For Investments, Ret             28784                         403743.76
                                   Mayor                                    2321                          366518.86
                                   Youth Comm Advisor                       22651                          26151.29
                                                                            44553                          63863.93

In [7]:
#resetting the index of the dataset to create a flat index
AvgSal = AvgSal.reset_index()

In [8]:
#Filtering the records of employees with overtime value more than 5% of Salaries
Ovrtime_ = AvgSal[AvgSal['Overtime'] > 0.05 * AvgSal['Salaries']]

Ovrtime_.head()

,Year,Job Family,Job,Employee Identifier,Salaries,Overtime,Other Salaries,Total Salary,Retirement,Health/Dental,Other Benefits,Total Benefits,Total Compensation
60,2013,Administrative-Labor & Trades,Bldgs & Grounds Maint Supt,27,114702.74,5771.40,21074.23,141548.37,23618.00,12918.24,9737.52,46273.76,187822.13
67,2013,Administrative-Labor & Trades,Bldgs & Grounds Maint Supt,19735,114249.03,25869.11,42914.37,183032.51,25115.00,12918.24,10377.81,48411.05,231443.56
68,2013,Administrative-Labor & Trades,Bldgs & Grounds Maint Supt,20763,114249.02,25905.57,10560.84,150715.43,23792.45,12918.24,9949.20,46659.89,197375.32
72,2013,Administrative-Labor & Trades,Bldgs & Grounds Maint Supt,48340,114249.06,6742.27,24304.48,145295.81,24024.73,12918.24,9946.73,46889.70,192185.51
76,2013,Administrative-Labor & Trades,Bldgs & Grounds Maint Supt,55134,114249.00,27945.50,8569.31,150763.81,23578.31,12918.24,10024.99,46521.54,197285.35

In [9]:
#Filtering out Job Family, Total Benefits and Total Compensation to a new dataframe
JobFamilyAvg = Ovrtime_[['Job Family', 'Total Benefits', 'Total Compensation']]
JobFamilyAvg = JobFamilyAvg.groupby(['Job Family']).mean()

In [10]:
#printing out the top 5 Job family data with average Benefits and Compensation
JobFamilyAvg.head()

#JobFamilyAvg.shape

                               Total Benefits  Total Compensation
Job Family
Administrative-DPW/PUC           51357.650000       211601.430000
Administrative-Labor & Trades    41122.252368       186782.600395
Agriculture & Horticulture       29897.497110       101394.261674
Airport Operation                35950.280841       131941.715101
Budget, Admn & Stats Analysis    26670.947073        92585.872683

In [11]:
#calculating the percentage total benefits columns based on Total Benefits and Total Compensation
JobFamilyAvg['Percent_Total_Benefit'] = (JobFamilyAvg['Total Benefits'] / JobFamilyAvg['Total Compensation']) * 100

In [12]:
JobFamilyAvg.head()

,Total Benefits,Total Compensation,Percent_Total_Benefit
Job Family,,,
Administrative-DPW/PUC,51357.650000,211601.430000,24.270937
Administrative-Labor & Trades,41122.252368,186782.600395,22.016104
Agriculture & Horticulture,29897.497110,101394.261674,29.486380
Airport Operation,35950.280841,131941.715101,27.247092
"Budget, Admn & Stats Analysis",26670.947073,92585.872683,28.806713

In [13]:
#reseting the index to make a flat index
JobFamilyAvg = JobFamilyAvg.reset_index()
JobFamilyAvg = JobFamilyAvg.sort_values(['Percent_Total_Benefit'], ascending=[False])
JobFamilyAvg.head()

,Job Family,Total Benefits,Total Compensation,Percent_Total_Benefit
39,Public Service Aide,13763.513296,38652.901089,35.607970
27,Park & Zoo,25637.061212,76441.045758,33.538344
25,Museum & Cultural Affairs,26548.462000,79514.714000,33.388112
11,Energy & Environment,14254.410000,43219.500000,32.981432
42,Revenue,18616.010937,58017.837187,32.086703

In [15]:
#function to check is directory exists
def funCheckDir(path):
    directory = os.path.dirname(path) # defining directory path
    if not os.path.exists(directory): # checking if directory already exists
        os.makedirs(directory) # making a directory

#printing the first csv with overtime data        
#resultsPath1 = b+"/Q2_Part_2_overtimeData.csv"

#printing the second csv with total compensation data
resultsPath2 = b+"/Q2_Part_2.csv"

#funCheckDir(resultsPath1)
funCheckDir(resultsPath2)

# Saving our result dataFrame to csv file.
#Ovrtime_.to_csv(resultsPath1, index=False, encoding='utf-8')
JobFamilyAvg.to_csv(resultsPath2, index=False, encoding='utf-8')

In [16]:
!jupyter nbconvert --to script Q2_Part_2.ipynb

[NbConvertApp] Converting notebook Q2_Part_2.ipynb to script
[NbConvertApp] Writing 3109 bytes to Q2_Part_2.py